import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import CreatePostWizard from "~/components/CreatePostWizard";
import PostView from "~/components/PostView";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();
  console.log({ data, user });

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-500 md:max-w-2xl">
          <div className="border-b border-slate-500 p-4">
            {!user?.isSignedIn && <SignInButton />}
            {user.isSignedIn && (
              <div>
                <CreatePostWizard />
              </div>
            )}
          </div>
          <div>
            {[...data!]?.map((postWithUser) => (
              <PostView
                postWithUser={postWithUser}
                key={postWithUser.post.id}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
