name: Node.js CI

on: [push, pull_request]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Type check with TypeScript
        run: npm run typecheck

      - name: Lint with ESLint
        run: npm run lint
